(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={items:[],type:'all',origin:null,query:''};
const cityCoords={صنعاء:[15.3694,44.1910],تعز:[13.5789,44.0219],إب:[13.9667,44.1833],عدن:[12.7855,45.0187],حضرموت:[15.9267,48.6275]};
const cityImages={صنعاء:'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Old_City_of_Sana%27a-111108.jpg/1280px-Old_City_of_Sana%27a-111108.jpg',تعز:'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/City_of_Taiz%2C_Yemen.jpg/960px-City_of_Taiz%2C_Yemen.jpg',إب:'https://upload.wikimedia.org/wikipedia/commons/d/d3/Ibb%2CYemen.jpg',عدن:'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Street_Scene_Aden_Yemen.jpg/1280px-Street_Scene_Aden_Yemen.jpg',حضرموت:'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/Shibam_Hadramaut.jpg/1280px-Shibam_Hadramaut.jpg'};
function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function km(a,b,c,d){const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p;return 2*R*Math.asin(Math.sqrt(Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2))}
async function geocode(q){if(cityCoords[q])return {lat:cityCoords[q][0],lon:cityCoords[q][1],display_name:q}; const parts=String(q||'').split(',').map(Number); if(parts.length===2&&parts.every(Number.isFinite))return {lat:parts[0],lon:parts[1],display_name:'موقعك الحالي'}; const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+encodeURIComponent(q));if(!r.ok)throw Error();const a=await r.json();if(!a[0])throw Error();return a[0]}
async function overpass(lat,lon){const radius=10000;const q=`[out:json][timeout:35];(nwr["tourism"~"hotel|guest_house|hostel|motel|apartment|resort"](around:${radius},${lat},${lon});nwr["amenity"~"restaurant|cafe|fast_food"](around:${radius},${lat},${lon}););out center tags;`;const urls=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.private.coffee/api/interpreter'];for(const u of urls){try{const r=await fetch(u,{method:'POST',body:q,headers:{'Content-Type':'text/plain','Accept':'application/json'}});if(r.ok){const j=await r.json();return j.elements||[]}}catch(e){}}throw Error()}
async function photoFor(name,city,fallback,tags={}){const direct=tags.image||tags['image:0'];if(direct)return direct;return fallback}
async function enrich(el,center,city){const t=el.tags||{};const name=t.name||t['name:ar']||t['name:en']||'مكان بدون اسم';const isRest=/restaurant|cafe|fast_food/.test(t.amenity||'');let lat=el.lat??el.center?.lat,lon=el.lon??el.center?.lon;let type=isRest?'restaurant':(t.tourism==='hotel'?'hotel':'stay');let img=await photoFor(name,city,cityImages[city]||'images.png',t);return {id:(el.type||'x')+'-'+el.id,name,lat,lon,type,city,img,rating:t.stars?Number(t.stars):null,phone:t.phone||t['contact:phone']||'',website:t.website||t['contact:website']||'',hours:t.opening_hours||'',cuisine:t.cuisine||'',dist:km(center.lat,center.lon,lat,lon),raw:t}}
function label(x){return x.type==='restaurant'?'🍽️ مطعم':x.type==='hotel'?'🏨 فندق':'🏠 إقامة'}
function card(x){const saved=(JSON.parse(localStorage.getItem('rahal-service-favs')||'[]')).includes(x.id);return `<article class="card service-card"><img src="${esc(x.img)}" alt="${esc(x.name)}" loading="lazy" onerror="this.onerror=null;this.src='${esc(cityImages[x.city]||'images.png')}'"><div class="cardbody"><h3>${label(x)} ${esc(x.name)}</h3><div class="muted">${esc(x.city)} · ${x.dist.toFixed(1)} كم</div><div class="meta"><span>${x.rating?'★ '+x.rating:'⭐ بيانات التقييم غير متوفرة'}</span><span>${x.cuisine?'🍴 '+esc(x.cuisine):''}</span></div><p>${x.hours?'🕐 '+esc(x.hours):'📍 موقع متاح على الخريطة'}${x.phone?' · 📞 '+esc(x.phone):''}</p><div class="card-actions"><button class="btn primary" data-map="${x.lat},${x.lon}">🗺️ الخريطة</button><button class="btn" data-route="${x.lat},${x.lon}">🧭 الاتجاهات</button><button class="btn" data-save="${esc(x.id)}">${saved?'❤️ محفوظ':'♡ حفظ'}</button></div></div></article>`}
function render(){let a=state.items.filter(x=>state.type==='all'||x.type===state.type);if($('#sortServices').value==='name')a.sort((x,y)=>x.name.localeCompare(y.name,'ar'));else a.sort((x,y)=>x.dist-y.dist);$('#servicesGrid').innerHTML=a.length?a.map(card).join(''):'<div class="notice full">لا توجد أماكن مطابقة ضمن النطاق الحالي.</div>';$$('[data-map]').forEach(b=>b.onclick=()=>{const [lat,lng]=b.dataset.map.split(',');location.href=`map.html?lat=${lat}&lng=${lng}&service=1`});$$('[data-route]').forEach(b=>b.onclick=()=>{const [lat,lng]=b.dataset.route.split(',');if(state.origin){location.href=`map.html?lat=${lat}&lng=${lng}&route=1&fromLat=${state.origin.lat}&fromLng=${state.origin.lon}`}else location.href=`map.html?lat=${lat}&lng=${lng}&route=1`});$$('[data-save]').forEach(b=>b.onclick=()=>{let a=JSON.parse(localStorage.getItem('rahal-service-favs')||'[]'),i=a.indexOf(b.dataset.save);i<0?a.push(b.dataset.save):a.splice(i,1);localStorage.setItem('rahal-service-favs',JSON.stringify(a));b.textContent=i<0?'❤️ محفوظ':'♡ حفظ';if(window.RahalDevice?.vibrate)RahalDevice.vibrate(15)});}
async function load(q,origin){$('#serviceStatus').textContent='⏳ جارٍ البحث عن الأماكن...';$('#servicesGrid').innerHTML='';try{const c=await geocode(q);const center={lat:Number(c.lat),lon:Number(c.lon)};const city=c.display_name?.split(',')[0]||q;let els=[];try{els=await overpass(center.lat,center.lon)}catch{};const selected=els.filter(e=>e.lat||e.center).sort((a,b)=>{const at=a.lat??a.center.lat,al=a.lon??a.center.lon,bt=b.lat??b.center.lat,bl=b.lon??b.center.lon;return km(center.lat,center.lon,at,al)-km(center.lat,center.lon,bt,bl)}).slice(0,140);state.items=selected.length?await Promise.all(selected.map(e=>enrich(e,center,city))):[{id:'offline-hotel-'+city,name:'أماكن الإقامة القريبة',lat:center.lat,lon:center.lon,type:'stay',city,img:cityImages[city]||'images.png',rating:null,phone:'',website:'',hours:'',cuisine:'',dist:0,raw:{}},{id:'offline-restaurant-'+city,name:'مطاعم قريبة',lat:center.lat,lon:center.lon,type:'restaurant',city,img:cityImages[city]||'images.png',rating:null,phone:'',website:'',hours:'',cuisine:'',dist:0,raw:{}}];state.origin=origin||center;state.query=q;$('#serviceStatus').textContent=selected.length?`✅ تم العثور على ${state.items.length} مكانًا قرب ${esc(city)}.`:`📴 لا توجد بيانات أماكن محلية لهذه المدينة؛ تم عرض نقاط إرشادية فقط.`;render()}catch(e){$('#serviceStatus').textContent='تعذر تحديد الموقع. اختر مدينة من القائمة أو اسمح بالموقع ثم حاول مرة أخرى.'}}
$$('[data-type]').forEach(b=>b.onclick=()=>{$$('[data-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.type=b.dataset.type;render()});$('#sortServices').onchange=render;$('#searchServices').onclick=()=>{const q=$('#serviceSearch').value.trim()||$('#citySelect').value.trim();if(q)load(q)};$('#citySelect').onchange=()=>{if($('#citySelect').value)load($('#citySelect').value)};$('#serviceSearch').onkeydown=e=>{if(e.key==='Enter'&&e.target.value.trim())load(e.target.value.trim())};$('#nearMeBtn').onclick=()=>{if(!navigator.geolocation)return alert('المتصفح لا يدعم تحديد الموقع');$('#serviceStatus').textContent='📍 جارٍ تحديد موقعك...';navigator.geolocation.getCurrentPosition(p=>{const o={lat:p.coords.latitude,lon:p.coords.longitude};load(`${o.lat},${o.lon}`,o)},()=>{$('#serviceStatus').textContent='تعذر تحديد موقعك. اسمح للموقع من إعدادات المتصفح. '})};})();